### ISSUE TITLE
Баг с роутами

### ISSUE THREAD

**Issue by Fer0x** [kohana-pack/Pagination#2]
Есть админка, имеющая такой общий роут:

``` php
Route::set('admin', 'admin(/<controller>(/<action>(/<id>(/<param>))))')
    ->defaults(array(
        'directory'  => 'admin',
        'controller' => 'main',
        'action'     => 'index',
    ));
```

При использовании модуля пагинации как есть в любом контроллере вида Controller_Admin_Example, ссылки на страницы представляются в виде '/admin/?page=x'. Т.е. имя котроллера не включается в url.

Быстрое решение -  добавление отдельного роута:

``` php
Route::set('admin/example', 'admin/example(/<action>/(<id>(/<param>)))')
    ->defaults(array(
    'directory'  => 'admin',
    'controller' => 'example',
    'action'     => 'index',
    'id' => '',
    'param' => ''
));
```

**Comment by biakaveron** [comment]
Отпишись в суппорт по поводу учетки. Там периодически такие проблемы возникают. Этот коммент я удалю
