### ISSUE TITLE
[Feature] Кол-во максимальных дополнений

### ISSUE THREAD

**Issue by Fer0x** [kohana-pack/Pagination#3]
Идея: избегать ситуаций, в которых на последней странице содержится 1-2 записей. Нужно присоединять их к предпоследней странице.
- добавить в конфиг $max_additional;
- учитывать $max_additional при расчете $total_pages
- нужна поддержка со стороны ORM

``` php
$this->total_pages        = (int) floor($this->total_items / $this->items_per_page);
if ($this->total_items % $this->items_per_page >= $this->max_additional)
{
    $this->total_pages++;
}
```

доп. информация: http://habrahabr.ru/qa/3198/

**Comment by Fedott** [comment]
А какая поддержка нужна со стороны ORM?

**Comment by biakaveron** [comment]
Никаких завязок с ORM. Ничего особенного ORM в этом плане не предоставит (по сравнению с обычными массивами данных), только лишняя зависимость от необязательного модуля.
